version: "3"

services:
  fhbackend:
    container_name: fh-backend
    image: fhbackend
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    links:
      - mongo
    
  mongo:
    container_name: mongo
    image: mongo


networks:
  default:
    external:
      name: scoobydoo