version: "3.4"

services:
  fhbackend:
    container_name: fh-backend
    image: fhbackend
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 1337:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
